### PR TITLE
feat/dayjs

### LINKED ISSUE #123: migrate from momentJs to dayJs
the team has decided to move from momentJs to dayJs, there are few places where we are using moment currently, we need to replace the code with dayJs

### PR DESCRIPTION
**Pull request by khushi818**
### What is the change?
 
The moment needed to be replaced by dayJs.

### Issues 

MomentLocalizer is not fixed. The other pr(#131) shows an error while running, the solution is not working. So I didn't make changes there rather raised a new pr.

### \*Dev Tested?

- [x] Yes
- [ ] No

#### Platforms

- [x] Web

#### Browsers

- [x] Chrome
- [ ] Safari
- [ ] Firefox

## Screenshots

image
image

closes #123

### CODE REVIEW

**Comment by harshith-venkatesh** [comment]
@khushi818 , could you please add a video or a screenshots showing the required screens where all the changes are working as expected.
The PR seems to be replacing moment with dayJS 
We need to confirm once before we merge our changes

**Review by isVivek99 — APPROVED** [review]
good job

**Review by samyakshah3008 — DISMISSED** [review]
Great work, Khushi!

**Review by samyakshah3008 — DISMISSED** [review]

**Review by samyakshah3008 — APPROVED** [review]

**Comment by harshith-venkatesh** [comment]
Thanks @khushi818 for ensuring all the impacted files are migrated from moment to dayJS

**Pull request merged**
