### PR TITLE
Feature 110 event card

### PR DESCRIPTION
**Pull request by Martijn0405**
### What is the change?

Added an event component as described in the issue description #110 using the Figma design

### Before / After Change Screenshots

image

### CODE REVIEW

**Comment by harshith-venkatesh** [comment]
We are looking to integrate the component with the already available modal currently integrated with the React Big Calendar.
The current changes include the presence of an array and event card currently being asked to be built.
Could you look into the way where the current event card gets integrated with the available modal that is being shown in home page please

**Comment by harshith-venkatesh** [comment]
@Martijn0405

**Comment by iRohitGaur** [comment]
@Martijn0405 we have waited for your response on this for sometime now. This PR will be closed without merge due to no response from your end.

**Comment by Martijn0405** [comment]
Apologies for the lack of communication. We will use your comments and implement a better solution.

**Comment by Martijn0405** [comment]
@iRohitGaur I committed an implementation of your requested changed, please review and open the PR again.

**Comment by iRohitGaur** [comment]
> @iRohitGaur I committed an implementation of your requested changed, please review and open the PR again.

@Martijn0405 The issue related to this PR is closed now as it resolved and merged in the codebase.

**Comment by Martijn0405** [comment]
@iRohitGaur  The PR is not merged to the code base, just the PR was closed. Do you prefer that I make I new PR of the same branch?

**Comment by iRohitGaur** [comment]
> @iRohitGaur The PR is not merged to the code base, just the PR was closed. Do you prefer that I make I new PR of the same branch?

Hi @Martijn0405 , I worked on this issue and the PR for that has been already merged in the codebase.

**Pull request closed without merging**
