### PR TITLE
refactor: comment onboarding step2

### LINKED ISSUE #185: comment out step 2 from Onboarding
- Step 2 from onboarding needs to be commented right now till we implement 3rd party calendar integration

### PR DESCRIPTION
**Pull request by iRohitGaur**
### What is the change?

commented step 2 of onboarding and redirected user to homepage.

Provide a small description of what did you change and provide the reference to the issue ticket.

closes #185

### CODE REVIEW

**Comment by isVivek99** [comment]
does this also solve the issue of get call being triggered when we go to `/` route

**Comment by iRohitGaur** [comment]
> does this also solve the issue of get call being triggered when we go to `/` route

No. That will be addressed separately as discussed with @harshith-venkatesh

**Comment by isVivek99** [comment]
> > does this also solve the issue of get call being triggered when we go to `/` route
> 
> @isVivek99 No. That will be addressed separately as discussed with @harshith-venkatesh

Can we create a seperate issue for that

**Comment by iRohitGaur** [comment]
> > > does this also solve the issue of get call being triggered when we go to `/` route
> > 
> > 
> > @isVivek99 No. That will be addressed separately as discussed with @harshith-venkatesh
> 
> Can we create a seperate issue for that

@isVivek99 yes that will be good. Can you create it? As you have more context with the issue.

**Comment by isVivek99** [comment]
look into https://github.com/Real-Dev-Squad/website-calendar/issues/187 next

**Review by isVivek99 — APPROVED** [review]

**Review by harshith-venkatesh — APPROVED** [review]

**Pull request merged**
